# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-08-24 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='list',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
